### ISSUE TITLE
Build the dev box (see vagrant_dev playbook) to use jetty and webrick instead of tomcat and apache

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#49]

**Comment by hackartisan** [comment]
Known issue: fedora doesn't run from a shared directory. Mark has been in contact with Andrew Woods on a fedora fix for this issue.

**Comment by mark-dce** [comment]
Mark hopes to have this done by or before Hydra Camp at the end of February.

**Comment by mark-dce** [comment]
There's an implied requirement here that you can run your development environment from a shared directory like /vagrant so that you can use a gui editor on the host environment.  So, we need to figure out a fix to the jetty-fedora not starting correctly when running on a vagrant share.

**Comment by hackartisan** [comment]
really wishing i had this these days to make interactive debugging easy.

**Comment by mark-dce** [comment]
working on it... ;)

If you're running Fedora 4.x using fcrepo_wrapper instead of hydra_jetty, you can tell Fedora to run using a different data directory and do this.

I got the manual instructions pinned down at the last hydra camp if you want to play around with them (you need to run solr & fedora using solr_wrapper & fcrepo_wrapper instead of using hydra_jetty).  If you want to give it a try, instructions are here: https://docs.google.com/document/d/1wnpJBS-Q9Yswp7r2fGfzvOzjjz0C971INU3pDfgZd8k/edit?usp=sharing - see the summary under "Starting services in a VM" under Wednesday Morning.  Maybe [The Dive into Hydra Solr & Fedora Lesson](https://github.com/projecthydra/hydra/wiki/Lesson---Start-FCRepo-and-Solr) gives better instructions.  You just need to append `-d path/data_directory` to have fcrepo_wrapper use a data directory that's somewhere not on the shared folders.

**Comment by hackartisan** [comment]
Your update reminds me (because I _do_ have a manual set up just like this!) that I'm not really using vagrant any more and what I really want is a dev build on a remote host. (this way I can access it without having to carry any particular computer around) So I am a bit of a unique use case but I hope any vagrant-specific shenanigans will be encapsulated somehow!

**Comment by mark-dce** [comment]
Agreed - we actually have a use case for the same thing - give folks an AWS box running the hydra-camp tutorials base build if they don't have a local system that can run the Vagrant version (because their system is underpowered, administratively locked down, etc.)

I'm gonna finish the Vagrant version first since I'm partway through, but I've added #110 for when the Vagrant version is complete.

**Comment by hackartisan** [comment]
Awesome!
