### ISSUE TITLE
set fedora_version in defaults instead of tasks

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#77]
This should be set as a default variable; ansible convention will cause users to look there for customizations they may want to make.

https://github.com/curationexperts/ansible-hydra/blob/master/roles/hydra-stack/install/tasks/fedora.yml#L5-L7

**Comment by mark-dce** [comment]
I actually did this because I wanted the playbook to give a warning in the log if the version hasn't been explicitly set - I couldn't figure out how to do that using a default.

The current version of ansible makes it hard to show the version in the task name:  

```
2015-12-17 12:53:02,866 p=47633 u=mark |  TASK: [hydra-stack/install | set fedora version if absent] ******************** 
2015-12-17 12:53:02,869 p=47633 u=mark |  skipping: [default]
2015-12-17 12:53:02,875 p=47633 u=mark |  TASK: [hydra-stack/install | fedora version to install 4.3.0] ***************** 
2015-12-17 12:53:02,877 p=47633 u=mark |  ok: [default] => {
    "msg": "Set 'fedora_version' in your variables to install a different version of Fedora Commons"
```

The current code could definitely be over-engineering on my part.  We could just leave a debug line in to show the version number.  But fedora doesn't use semantic versioning and there are breaking changes between 4.x versions, so I kinda wanted to force the issue of making a version selection somehow.

**Comment by hackartisan** [comment]
Yes, specifying a different version to install is a very standard use of variables in ansible. I also don't think you can assume that a user will be watching for a message like this.

If you truly want to force the user to specify a version, put a comment in defaults but then don't set it anywhere. The scripts will error.

However, I would still advocate for setting a default version in defaults/main.yml.
