### ISSUE TITLE
no package matching 'build-essential' is available

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#84]
This commit appears to break the build 0eb57648649c8cac9fc4a556b5d89d4c1722875d

Causes the task to be skipped altogether. Adding the following task after 'update apt cache' generates the following output. See "attempts: 0":

```
- name: ResultAfter
  debug:
    msg: "{{ result }}"
```

```
TASK: [packages | ResultAfter] ************************************************
ok: [54.173.137.233] => {
    "msg": {
        "attempts": 0,
        "changed": false,
        "invocation": {
            "module_args": "update_cache=yes",
            "module_complex_args": {},
            "module_name": "apt"
        }
    }
}
```

**Comment by acozine** [comment]
Looks like the return values of `update_cache` include `updated_cache` True/False - see https://github.com/ansible/ansible-modules-core/pull/909/files
so I think `until: updated_cache = True` would work in place of lines 10 and 11 from this commit.

**Comment by acozine** [comment]
Nope, it's a bug in ansible: https://github.com/ansible/ansible-modules-core/issues/1497.

**Comment by hackartisan** [comment]
@acozine hm. but update_cache seems to work fine for us with the register / until / retries lines removed.

**Comment by hackartisan** [comment]
Ugh... @sanfordd and I are continuing to get the error "no package matching 'build-essential' is available"

Still not clear what's causing this or why we've never seen it before. potentially not related to this commit after all.

**Comment by sanfordd** [comment]
So with help from @hackmastera we did a little testing and found out part of the issue.
When running the cache update (which to skip the issue was replaced with command: apt-get update) it grabs about 2 MB of repo updates. After the apt-get upgrade is run to update all packages to the most current version, it errors out when installing packages unless apt-get update is run to re-update the cache (downloading about 22 MB of data). If the cache is updated after the upgrade, the install moves fine. 

See the log below (apt-get update and apt-get upgrade were used in place of the ansible apt tools to get the details)

https://gist.github.com/sanfordd/1e8987a9790fccf3586b

**Comment by mark-dce** [comment]
I was running into the build_essential missing issue intermittently and added commit 0eb57648649c8cac9fc4a556b5d89d4c1722875d to try address it.  I'm happy to back it back out.  But in my experience, the missing build_essential error will continue to occur intermittently.  I think the issue is with cache update not completing successfuly as identified in the previous comment.  The issue seemed to occur more often the faster the machine I was running it against, so it might be worth adding back in a fixed delay task at the very end of the launch_ec2 main tasks here:
https://github.com/curationexperts/ansible-hydra/blob/master/roles/launch_ec2/tasks/main.yml#L37-L39

Just to clarify, that commit only occurs on ec2 instances (that's where the commit in question would have effect) or are folks seeing it in vagrant builds as well?

**Comment by hackartisan** [comment]
The retries are not the problem, but they also are not a solution. It seems to be working pretty consistently for us to put an update both before and after the upgrade.

We could try it with a delay task as well. How long a delay do you think we might need?

We're definitely not sure what the root cause is.

The commit affects the packages role which is used in both create_ec2.yml and configure.yml. However, we have not been running vagrant builds so can't comment on the impact there. But yeah I don't think that commit is the issue anyway.

**Comment by mark-dce** [comment]
I've been running with this at the end of my launch_ec2 role and haven't been able to duplicate the issue since:

```
- name: pause another few seconds for other services to start
  pause: seconds=5
```

I just committed this and removed the retries as 4ff25878113f26ab36e586ab8acdfc2b3b81ba7f.  Can folks test this update and see if they still see the issue?

**Comment by sanfordd** [comment]
Using a short pause does seem to fix the issue nicely in a few tests.

**Comment by hackartisan** [comment]
@mark-dce I've tested your fix and it works for me! Thanks!
