### ISSUE TITLE
ansible_ssh_user: a variable without a default?

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#96]
It doesn't look like we're providing a default value for this new variable.

**Comment by acozine** [comment]
Indeed, we're not. This is a standard Ansible variable - if not otherwise set, it picks up the value set for 'user' or 'remote_user' in the main playbook file (so it uses 'vagrant' for Vagrant builds, 'ubuntu' or 'centos' for ec2 builds) or the value of the -u flag from the command line. I'm not sure what a sensible default for this variable would be, unless we're going to choose a standard target environment - but the variable currently works across target environments/OS's with no default.
Thoughts @hackmastera @mark-dce?

**Comment by hackartisan** [comment]
Ah, right!! That makes sense; I remember now all the automatically-available ansible variables start with ansible_. I think that's convention enough and you're right that adding a default would mess up the way it is supposed to work. Thanks for the reminder!!
